FROM node:18 AS builder

WORKDIR /grafana-plugin

COPY ./grafana-plugin /grafana-plugin

RUN npm install -g pnpm

RUN pnpm install

COPY . .

RUN pnpm build

FROM grafana/grafana:11.2.0

WORKDIR /etc/mocloud/grafana-plugins

COPY --from=builder /grafana-plugin/dist /etc/mocloud/grafana-plugins/moc-oncall-app