# Generated by Django 4.2.11 on 2024-07-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0051_remove_escalationpolicy_custom_button_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='deploy_env',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
    ]
