# Generated by Django 4.2.11 on 2024-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0052_alertgroup_deploy_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='alert_severity',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='alert_team',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
    ]
