# Generated by Django 4.2.11 on 2024-09-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0053_alertgroup_alert_severity_alertgroup_alert_team'),
        ('alerts', '0058_alter_alertgroup_reason_to_skip_escalation'),
    ]

    operations = [
    ]
