name: release_aliyun

on:
  push:
    branches:
    - mo
    - hotfix-*
  release:
    types:
    - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: login to aliyun acr
        uses: aliyun/acr-login@v1
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ALIYUN_DOCKER_USER }}"
          password: "${{ secrets.ALIYUN_DOCKER_PASSWORD }}"
          region-id: cn-hangzhou

      - name: set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.cn-hangzhou.aliyuncs.com/ack-cos/oncall
          tags: |
            type=sha
            type=ref,event=branch,suffix=-{{date 'YYYYMMDD'}}
            type=semver,pattern={{version}}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: engine
          build-args: |
            GITHUB_ACCESS_TOKEN=${{ secrets.TOKEN_ACTION }}
          file: engine/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      